// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp5e3Hxvr8sT6tLu-Qy8kjnTkrZbbPdvA',
    appId: '1:864058057724:android:7c749b70e5020c0f430879',
    messagingSenderId: '864058057724',
    projectId: 'pyquiz-a7102',
    storageBucket: 'pyquiz-a7102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDajU3IONCaoIEHf1F6VzekBlOno5ylQYg',
    appId: '1:864058057724:ios:c4ace08131ab100e430879',
    messagingSenderId: '864058057724',
    projectId: 'pyquiz-a7102',
    storageBucket: 'pyquiz-a7102.appspot.com',
    iosClientId: '864058057724-j0h3p1nfgn3iado31chodu761bqrkii1.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.flutter.app',
  );
}
